name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./registration/pom.xml
          mvn clean package -f ./management/pom.xml
          mvn clean package -f ./contractor/pom.xml
          mvn clean package -f ./mypage/pom.xml

      - name: Docker Build and push for Registration
        uses: docker/build-push-action@v4
        with:
          context: ./registration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/registration:latest
            ghcr.io/${{ github.repository }}/registration:${{ github.ref_name }}
            
      - name: Docker Build and push for Management
        uses: docker/build-push-action@v4
        with:
          context: ./management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/management:latest
            ghcr.io/${{ github.repository }}/management:${{ github.ref_name }}
            
      - name: Docker Build and push for Contractor
        uses: docker/build-push-action@v4
        with:
          context: ./contractor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/contractor:latest
            ghcr.io/${{ github.repository }}/contractor:${{ github.ref_name }}
            
      - name: Docker Build and push for Mypage
        uses: docker/build-push-action@v4
        with:
          context: ./mypage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
